int32 recording_time
bool avg_microphone_amplitudes
---
float32[] avg_dbs_robot_0 # Average dBs for microphones of robot 0 over recording time
float32[] avg_dbs_robot_1 # Average dBs for microphones of robot 1 over recording time
float32[] avg_dbs_robot_2 # Average dBs for microphones of robot 2 over recording time
---
float32 feedback # Feedback over the current running goal (perhaps % of completion or state?)
