# Please do not change the enum of these constants since it is hardcoded in the source code
int32 MODULE_RIGHT_MOTOR=0 # Range [-2000 ... 2000]
int32 MODULE_LEFT_MOTOR=1 # Range [-2000 ... 2000]
int32 MODULE_NORMAL_LED=2 # LEDs on/off flag: bit0 for LED1, bit1 for LED3, bit2 for LED5, bit3 for LED7
int32 MODULE_SPEAKER=3 # Sound id = [0,1,2]
int32 MODULE_RGB_LED_2=4 # Range [0 (off) ... 100 (max)] bit0 = r, bit1 = g, bit2 = b
int32 MODULE_RGB_LED_4=5
int32 MODULE_RGB_LED_6=6
int32 MODULE_RGB_LED_8=7


int32 module # Module to which the given value is to be applied to
int32 value # New value to be set for the 
int32[3] rgb # Set if the module is a rgb_led [0] = r, [1] = g, [2] = d
---
bool success # Will allways be true